# Generated by Django 4.2.5 on 2023-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('tamanho', models.CharField(choices=[('1l', '1 Litro'), ('2l', '2 Litros'), ('5l', '5 Litros'), ('10l', '10 Litros')], default='1l', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Picole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=20)),
                ('preco', models.FloatField()),
                ('tipo', models.CharField(choices=[('COB', 'Cobertura'), ('NORMAL', 'Normal')], default='NORMAL', max_length=6)),
                ('estoque', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=20)),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('tamanho', models.CharField(choices=[('250ml', '250ml'), ('1l', '1 Litro')], default='1l', max_length=5)),
            ],
        ),
    ]
