# Generated by Django 4.2.5 on 2023-09-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_picole_estoque_alter_picole_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acai',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='sorvete',
            name='tamanho',
        ),
    ]
