# Generated by Django 4.2.5 on 2023-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_acai_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picole',
            name='tipo',
            field=models.CharField(choices=[('Cobertura', 'Cobertura'), ('Sem cobertura', 'Sem cobertura')], default='Sem cobertura', max_length=13),
        ),
    ]
