# Generated by Django 4.2.5 on 2023-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_customer_order_ordersorvete_orderpicole_orderacai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
