# Generated by Django 4.2.5 on 2023-09-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_order_customer_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderacai',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderacai',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderpicole',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpicole',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordersorvete',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordersorvete',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAcai',
        ),
        migrations.DeleteModel(
            name='OrderPicole',
        ),
        migrations.DeleteModel(
            name='OrderSorvete',
        ),
    ]
