# Generated by Django 4.2.5 on 2023-10-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_rename_shopcart_shopcartpicole_shopcartsorvete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCartAcai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.acai')),
            ],
        ),
    ]
